a=open("people1.txt","w")
a.write("priyanka - shimla")
a.write("neela - delhi")
a.write("sashi - jaipur")
a.write("sarika - delhi")
a.write("deepti - shimla")
a.write("harshad - delhi")
a.write("trishna - delhi")
a.write("pradeep - jaipur")
a.write("sekhar - delhi")
a.write("nand - delhi")
a.write("anoop - delhi")
a.write("balwinder - jaipur")

a.close()

my_file = open("people1.txt")
file_data = my_file.read()
print (file_data)
my_file.close()

my_file2 = open("people2.txt", "w")
my_file2.write("Abhishek - Gurgaon")
my_file2.write("Ranveer - Delhi")
my_file2.close()

my_file3 = open("people3.txt", "w")
# my_file3.write("Abhishek - Gurgaon\n")
# my_file3.write("Ranveer - Delhi")
my_file3.write("Abhishek - Gurgaon\nRanveer - Delhi")
my_file3.close()